### ISSUE TITLE
what’s the meaning of dummy pass

### ISSUE THREAD

**Issue by Yonglinz77** [Vampire-Vx/Maml#1]
thx you so much for your brilliant repo, just have a question about your outer-loop updates, I get confused about replacing sum_task_gradients with dummy gradients. The FOMAML update is based on the sum_task_gradients, right? I don't get the meaning of dummy pass, can you kindly provide some detail about that?

Thx again

**Comment by Vampire-Vx** [comment]
> thx you so much for your brilliant repo, just have a question about your outer-loop updates, I get confused about replacing sum_task_gradients with dummy gradients. The FOMAML update is based on the sum_task_gradients, right? I don't get the meaning of dummy pass, can you kindly provide some detail about that?
> 
> Thx again

Yes, you are right. The FOMAMAL update is based on the sum_task_gradients. The dummy input is used to rebuild the computation graph, thus when backward is carried out, hook functions will be activated to replace dummy gradients with true sum_task_gradients.

**Comment by Yonglinz77** [comment]
thank you for your reply.
Vampire-Vx <notifications@github.com> 于2020年7月20日周一 上午4:15写道：
